### ISSUE TITLE
Quikstart datadog_integration_api_call_v2.yaml parameters were updated but the custom resource itself does not support update

### ISSUE THREAD

**Issue by vilikin** [DataDog/cloudformation-template#102]
## Expected Behavior

I would have expected `datadog_integration_api_call_v2.yaml` to not require updates, but now our stack is requiring this resource to be updated because the parameters were changed in [this commit](https://github.com/DataDog/cloudformation-template/commit/98896d2002c2f67c8ff517e6214c9a59fefaf08c).

Additionally, it was made in the same commit to not allow updates at all, but to fail on them instead of being a silent no-op like previously. So now our pipelines are stuck as the stack would need to be updated, but it does not support updates.

I would expect such bigger changes to be applied in a new version of the template. And I fail to understand the rationale behind the change: requiring update but not allowing update at the same time? Could you elaborate on the rationale behind the change and how customer's are expected to handle this situation? @sabiurr 

## Actual Behavior

Stack requires update because of changed parameters, but does not support update.

## Steps to Reproduce the Problem

  1. Deploy previous version of a stack based on `datadog_integration_api_call_v2.yaml`
  1. Try to update the stack (pulling the latest version of the file)
  1. See it fail because it does not support update

## Specifications

  - Datadog CloudFormation template version: `datadog_integration_api_call_v2.yaml`
  
## Stacktrace
  
  ```
  Update not supported, no operation performed.
  ```

**Comment by andyshinn** [comment]
Noticing this as well. I raised https://github.com/DataDog/cloudformation-template/issues/86 related to this as an ask to get stuff versioned in some way that we can pull templates that don't get updated from under our noses.

**Comment by JustinLiang90** [comment]
Noticed as well - Here is the PR introducing it. https://github.com/DataDog/cloudformation-template/commit/98896d2002c2f67c8ff517e6214c9a59fefaf08c

<img width="1844" alt="Screenshot 2024-05-05 at 8 55 29 PM" src="https://github.com/DataDog/cloudformation-template/assets/56423784/c9323548-0b33-4cc4-8b66-3f92b58da913">

**Comment by PPan1215** [comment]
This is occurring to me too.

**Comment by ribhavjain** [comment]
This is occurring for us too and we've seen some behavior occasionally deleting our stack entirely (and therefore the integration) after failed updates.

**Comment by sabiurr** [comment]
This has been reverted https://github.com/DataDog/cloudformation-template/pull/111

Can you try again and see if it works?
