### ISSUE TITLE
New updates in datadog_integration_api_call_v2.yaml make the lambda failed to update integration and then delete integration

### ISSUE THREAD

**Issue by JustinLiang90** [DataDog/cloudformation-template#107]
## Expected Behavior

The lambda embedded in the `datadog_integration_api_call_v2.yaml` should return
`SUCCESS` not `FAILED` if `Update not supported, no operation performed.` 
So that it will not return error to the AWS Cloudformation deployment, then it won't 
block the stack deployment to continue.

## Actual Behavior

Our AWS Cloudformation deployment failed because of the embedded lambda in
`datadog_integration_api_call_v2.yaml` returns 400 bad request because of 
`Update not supported, no operation performed.`

This makes the AWS Cloudformation trigger rollback and delete the entire Datadog
integration in the following action. See the below screenshot, the log is printted
by the lambda itself.

We cannot re-created the integration because it may be deleted again after
get `Update not supported, no operation performed.` error.

<img width="700" alt="Screenshot 2024-05-05 at 8 32 57 PM" src="https://github.com/DataDog/cloudformation-template/assets/56423784/bcc2120e-1089-442f-804a-c7fc105f52fe">

## Steps to Reproduce the Problem

1. Deploy previous version of a stack based on datadog_integration_api_call_v2.yaml.
2. Try to update the stack (pulling the latest version of the file).
3. See it fail because it does not support update.

## Specifications

  - Datadog CloudFormation template version:  datadog_integration_api_call_v2.yaml
  
## Stacktrace
  
  ```
  Update not supported, no operation performed.
  ```
  
## Related PR

https://github.com/DataDog/cloudformation-template/pull/100

**Comment by sabiurr** [comment]
This has been reverted https://github.com/DataDog/cloudformation-template/pull/111

can you try again and see if it is fixed?

**Comment by JustinLiang90** [comment]
It works for now. Thank you!!
