### ISSUE TITLE
NoEcho on ApiKey

### ISSUE THREAD

**Issue by sam-chen-zocdoc** [DataDog/cloudformation-template#48]
## Expected Behavior
ApiKey to be masked in StackSet

## Actual Behavior
The ApiKey is expose on StacksetName DatadogStreams  https://github.com/DataDog/cloudformation-template/blob/master/aws_streams/streams_main.yaml#L208

Request: add `NoEcho: true` to https://github.com/DataDog/cloudformation-template/blob/master/aws_streams/streams_single_region.yaml#L4-L9

**Comment by ktmq** [comment]
`NoEcho: true` is present on `ApiKey` parameters
https://github.com/DataDog/cloudformation-template/blob/2c350dc3411f9276abdb54ae4f13860ac582dbc6/aws_streams/streams_main.yaml#L9
