### ISSUE TITLE
Upgrade lambda runtimes used by Datadog AWS integration

### ISSUE THREAD

**Issue by bellmatt** [DataDog/cloudformation-template#58]
## Expected Behavior
Lambda functions involved in Datadog AWS Integration use supported runtimes 

## Actual Behavior
DatadogPolicyMacro lambda function uses the python3.7 runtime which relies on Amazon Linux 1, which is no longer supported after June 30th 2023:
https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/

The function affected is here:
https://github.com/DataDog/cloudformation-template/blob/master/aws/datadog_policy_macro.yaml#L13

## Steps to Reproduce the Problem

  1. Install the Datadog AWS integration using the CloudFormation templates supplied in this repo

## Specifications

  - Datadog CloudFormation template version:  latest
  
## Stacktrace
  
n/a

**Comment by mbant** [comment]
Other than the [already mentioned EOL for AL1](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/), Python 3.7 will also [no longer receive security patches](https://endoflife.date/python) since end of June 2023.

An update on this (or an approval / merge on #60) would be great!

**Comment by mbant** [comment]
@RaphaelAllier @upp22 anything holding this change and the associated https://github.com/DataDog/cloudformation-template/pull/60 back?

Pings as the two most recent committers, happy to be redirected :)

**Comment by bellmatt** [comment]
I just checked this and it looks like there is a [release.sh](https://github.com/DataDog/cloudformation-template/blob/master/aws/release.sh) in this repo that still needs to be run to update the templates in the S3 buckets, so this issue is unfortunately not fully resolved yet
