### ISSUE TITLE
Missing cloudwatch:TagResource permissions

### ISSUE THREAD

**Issue by billyshambrook** [DataDog/cloudformation-template#66]
## Actual Behavior

Am getting the following error when executing the `streams_main.yaml`

```
Resource handler returned message: "Resource of type 'Stack set operation [00000000-0000-0000-0000-000000000000] was unexpectedly stopped or failed. status reason(s): [ResourceLogicalId:DatadogMetricStreamAllNamespaces, ResourceType:AWS::CloudWatch::MetricStream, ResourceStatusReason:Resource handler returned message: "Invalid request provided: User: arn:aws:sts::1234567890123:assumed-role/DatadogStreamStackSetExecutionRole/00000000-0000-0000-0000-000000000000 is not authorized to perform: cloudwatch:TagResource on resource: arn:aws:cloudwatch:ap-south-1:1234567890123:metric-stream/datadog-metrics-stream because no identity-based policy allows the cloudwatch:TagResource action" (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: InvalidRequest).]' with identifier 'DatadogStreams:00000000-0000-0000-0000-000000000000' did not stabilize." (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: NotStabilized)
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Datadog CloudFormation template version:  
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by ktmq** [comment]
Hi! This permission was added in an update we made in Aug 2024.
  
PR: https://github.com/DataDog/cloudformation-template/pull/136
Commit: https://github.com/DataDog/cloudformation-template/pull/136/commits/f38e6d898da4b9d648e068fbfb03a3874ec8bd4f#diff-ed2e92912195e1cf24711250222812f07122bb7d2273e08ddf015d65b96e1323R153

Ensuring that you are using the latest version of this template should resolve the issue.
