### ISSUE TITLE
Policy Macro Template referenced from main.yaml is still on python 3.7

### ISSUE THREAD

**Issue by fszymanski-blvd** [DataDog/cloudformation-template#72]
While looking into the python 3.7 lambda deprecation, I updated the datadog integration cloudformation template which fixed the python version of the forwarder lambda but not the policy macro lambda. 

Digging in, I found that while the [policy macro has been updated to python 3.9](https://github.com/DataDog/cloudformation-template/blob/master/aws/datadog_policy_macro.yaml#L13), the [template in S3 that is used by main.yaml ](https://github.com/DataDog/cloudformation-template/blob/master/aws/main.yaml#L113)still is on python 3.7.

**Comment by plumdog** [comment]
Per @RaphaelAllier's comment https://github.com/DataDog/cloudformation-template/pull/60#issuecomment-1713725803, the relevant change is now released:
```
$ curl -s 'https://datadog-cloudformation-template.s3.amazonaws.com/aws/datadog_policy_macro.yaml' | yq .Resources.DatadogPolicyMacroMacroFunction.Properties.Runtime
python3.9
```

**Comment by fszymanski-blvd** [comment]
> Per @RaphaelAllier's comment [#60 (comment)](https://github.com/DataDog/cloudformation-template/pull/60#issuecomment-1713725803), the relevant change is now released:
> 
> ```
> $ curl -s 'https://datadog-cloudformation-template.s3.amazonaws.com/aws/datadog_policy_macro.yaml' | yq .Resources.DatadogPolicyMacroMacroFunction.Properties.Runtime
> python3.9
> ```

Thanks for the notification. I have a support ticket open about this right now so maybe that kickstarted something. I've confirmed that updating the root template properly updates the lambda

**Comment by RaphaelAllier** [comment]
I was taking care of this but went on PTO,
Apologize for the delay
